name: Deploy-feat-admin-zfinance
on:
  push: 
    branches:
      - main
permissions: 
  contents: write
jobs:
  deploy:
    name: run-on-machine
    runs-on: ubuntu-24.04

    steps:
      - name: chekout-repository-code-in-vm
        uses: actions/checkout@v4

      - name: ssh-deployement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd  /var/www/zfinancesdrc.com/
            echo ${{ secrets.PASSWORD }} | sudo -S git pull origin main 
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl restart nginx